### ISSUE TITLE
Failed to activate the winter-syntax theme

### ISSUE THREAD

**Issue by jm06487** [matthewwithanm/atom-winter-syntax#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [winter-syntax](https://github.com/matthewwithanm/atom-winter-syntax) package, v2.2.5
### Stack Trace

Failed to activate the winter-syntax theme

```
At variable @orange-highlight is undefined in C:\Users\personal\.atom\packages\winter-syntax\stylesheets\editor.less:85:14

LessError: variable @orange-highlight is undefined
  at C:\Users\personal\.atom\packages\winter-syntax\stylesheets\editor.less:85:14
```
### Commands

```
     -0:14 core:paste (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by matthewwithanm** [comment]
Woah, sorry I didn't respond to this! I wasn't watching the repo 😞

But it should be good now!
